/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhotographyIndexRouteImport } from './routes/photography/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as PhotographySectionIdRouteImport } from './routes/photography/$sectionId'
import { Route as BlogPostIdRouteImport } from './routes/blog/$postId'

const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyIndexRoute = PhotographyIndexRouteImport.update({
  id: '/photography/',
  path: '/photography/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographySectionIdRoute = PhotographySectionIdRouteImport.update({
  id: '/photography/$sectionId',
  path: '/photography/$sectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPostIdRoute = BlogPostIdRouteImport.update({
  id: '/blog/$postId',
  path: '/blog/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/showcase': typeof ShowcaseRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/photography/$sectionId': typeof PhotographySectionIdRoute
  '/blog': typeof BlogIndexRoute
  '/photography': typeof PhotographyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/showcase': typeof ShowcaseRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/photography/$sectionId': typeof PhotographySectionIdRoute
  '/blog': typeof BlogIndexRoute
  '/photography': typeof PhotographyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/showcase': typeof ShowcaseRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/photography/$sectionId': typeof PhotographySectionIdRoute
  '/blog/': typeof BlogIndexRoute
  '/photography/': typeof PhotographyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/showcase'
    | '/blog/$postId'
    | '/photography/$sectionId'
    | '/blog'
    | '/photography'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/showcase'
    | '/blog/$postId'
    | '/photography/$sectionId'
    | '/blog'
    | '/photography'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/showcase'
    | '/blog/$postId'
    | '/photography/$sectionId'
    | '/blog/'
    | '/photography/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ShowcaseRoute: typeof ShowcaseRoute
  BlogPostIdRoute: typeof BlogPostIdRoute
  PhotographySectionIdRoute: typeof PhotographySectionIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  PhotographyIndexRoute: typeof PhotographyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography/': {
      id: '/photography/'
      path: '/photography'
      fullPath: '/photography'
      preLoaderRoute: typeof PhotographyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography/$sectionId': {
      id: '/photography/$sectionId'
      path: '/photography/$sectionId'
      fullPath: '/photography/$sectionId'
      preLoaderRoute: typeof PhotographySectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$postId': {
      id: '/blog/$postId'
      path: '/blog/$postId'
      fullPath: '/blog/$postId'
      preLoaderRoute: typeof BlogPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ShowcaseRoute: ShowcaseRoute,
  BlogPostIdRoute: BlogPostIdRoute,
  PhotographySectionIdRoute: PhotographySectionIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  PhotographyIndexRoute: PhotographyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
